import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();
const statements = [
  'CREATE TABLE IF NOT EXISTS "InventoryItem" ("id" TEXT NOT NULL PRIMARY KEY, "sku" TEXT, "labelCode" TEXT, "name" TEXT NOT NULL, "description" TEXT NOT NULL DEFAULT \'\', "category" TEXT NOT NULL DEFAULT \'未分類\', "quantity" INTEGER NOT NULL DEFAULT 0, "unit" TEXT NOT NULL DEFAULT \'件\', "location" TEXT NOT NULL DEFAULT \'未指定\', "minimumStock" INTEGER NOT NULL DEFAULT 0, "status" TEXT NOT NULL DEFAULT \'Unchecked\', "remark" TEXT NOT NULL DEFAULT \'\', "lastCheckedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "archivedAt" DATETIME)',
  'CREATE UNIQUE INDEX IF NOT EXISTS "InventoryItem_sku_key" ON "InventoryItem"("sku")',
  'CREATE UNIQUE INDEX IF NOT EXISTS "InventoryItem_labelCode_key" ON "InventoryItem"("labelCode")',
  'CREATE TABLE IF NOT EXISTS "CheckSession" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "locationFilter" TEXT, "categoryFilter" TEXT, "status" TEXT NOT NULL DEFAULT \'ACTIVE\', "startedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)',
  'CREATE TABLE IF NOT EXISTS "CheckLog" ("id" TEXT NOT NULL PRIMARY KEY, "sessionId" TEXT, "itemId" TEXT NOT NULL, "detectedValue" TEXT NOT NULL, "detectionMethod" TEXT NOT NULL, "confidence" REAL NOT NULL DEFAULT 1, "previousStatus" TEXT NOT NULL, "newStatus" TEXT NOT NULL, "checkedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "checkedBy" TEXT NOT NULL DEFAULT \'Admin\', CONSTRAINT "CheckLog_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "CheckSession" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "CheckLog_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "InventoryItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE)',
  'CREATE INDEX IF NOT EXISTS "CheckLog_sessionId_itemId_idx" ON "CheckLog"("sessionId", "itemId")',
  'CREATE TABLE IF NOT EXISTS "AuditLog" ("id" TEXT NOT NULL PRIMARY KEY, "itemId" TEXT NOT NULL, "action" TEXT NOT NULL, "source" TEXT NOT NULL, "previousValue" TEXT, "newValue" TEXT, "quantityChange" INTEGER, "performedBy" TEXT NOT NULL DEFAULT \'Admin\', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "InventoryItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE)',
  'CREATE TABLE IF NOT EXISTS "ImportJob" ("id" TEXT NOT NULL PRIMARY KEY, "fileName" TEXT NOT NULL, "insertedCount" INTEGER NOT NULL DEFAULT 0, "updatedCount" INTEGER NOT NULL DEFAULT 0, "skippedCount" INTEGER NOT NULL DEFAULT 0, "errorCount" INTEGER NOT NULL DEFAULT 0, "errors" TEXT NOT NULL DEFAULT \'[]\', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)'
];
async function main(){for(const sql of statements) await db.$executeRawUnsafe(sql)}
main().finally(()=>db.$disconnect());
